use bond_vault_v2::bond_vault_v2::BondVaultV2ContractRef;
use delivery_contradiction_verifier_v2::delivery_contradiction_verifier_v2::DeliveryContradictionVerifierV2ContractRef;
use duplicate_claim_verifier_v2::duplicate_claim_verifier_v2::DuplicateClaimVerifierV2ContractRef;
use invoice_pool_v2::invoice_pool_v2::InvoicePoolV2ContractRef;
use odra::{casper_types::{bytesrepr::Bytes, U256}, prelude::*, ContractRef};

const TOKEN_UNIT: u64 = 1_000_000_000;

#[odra::odra_type]
#[derive(Default)]
pub enum ActionStatusV2 { #[default] Initiated, Bonded, Executed, Challenged, ResolvedSlash, ResolvedRefund }
#[odra::odra_type]
pub struct ActionV2 { pub agent: Address, pub invoice_id: u64, pub claim_hash: Bytes, pub amount: U256, pub reasoning_hash: Bytes, pub bond_required: U256, pub bond_posted: U256, pub window_end: u64, pub status: ActionStatusV2, pub challenger: Option<Address>, pub fault_class: String, pub evidence_root: Bytes }
#[odra::odra_type]
#[derive(Default)]
pub struct RepV2 { pub clean: u32, pub slashed: u32, pub score: i64 }
#[odra::event]
pub struct ActionInitiatedV2 { pub action_id: u64, pub agent: Address, pub invoice_id: u64, pub amount: U256, pub bond_required: U256 }
#[odra::event]
pub struct ActionChallengedV2 { pub action_id: u64, pub challenger: Address, pub fault_class: String, pub evidence_root: Bytes }
#[odra::event]
pub struct ResolvedSlashV2 { pub action_id: u64, pub challenger: Address, pub challenger_amount: U256, pub reserve_amount: U256, pub fault_class: String, pub evidence_root: Bytes }
#[odra::odra_error]
pub enum Error { ActionNotFound = 1, NotAgent = 2, InvalidStatus = 3, InsufficientBond = 4, InvalidBasisPoints = 5, NotOwner = 6, PoolFinalized = 7, UnregisteredVerifier = 8, FaultNotConfirmed = 9, ChallengeWindowClosed = 10, WindowStillOpen = 11 }

#[odra::module(events = [ActionInitiatedV2, ActionChallengedV2, ResolvedSlashV2], errors = Error)]
pub struct BondsmanControllerV2 { owner: Var<Address>, vault: Var<Address>, pool: Var<Address>, pool_finalized: Var<bool>, token: Var<Address>, next_action_id: Var<u64>, actions: Mapping<u64, ActionV2>, reputation: Mapping<Address, RepV2>, window_secs: Var<u64>, challenger_bps: Var<u32>, fault_verifiers: Mapping<String, Address> }

#[odra::module]
impl BondsmanControllerV2 {
    pub fn init(&mut self, vault: Address, pool: Address, token: Address, window_secs: u64, challenger_bps: u32) { if challenger_bps > 10_000 { self.env().revert(Error::InvalidBasisPoints); } self.owner.set(self.env().caller()); self.vault.set(vault); self.pool.set(pool); self.pool_finalized.set(false); self.token.set(token); self.window_secs.set(window_secs); self.challenger_bps.set(challenger_bps); self.next_action_id.set(0); }
    pub fn set_pool(&mut self, pool: Address) { self.owner(); if self.pool_finalized.get_or_default() { self.env().revert(Error::PoolFinalized); } self.pool.set(pool); self.pool_finalized.set(true); }
    pub fn register_verifier(&mut self, fault_class: String, verifier: Address) { self.owner(); self.fault_verifiers.set(&fault_class, verifier); }
    pub fn initiate_action(&mut self, invoice_id: u64, claim_hash: Bytes, amount: U256, reasoning_hash: Bytes) -> u64 { let agent = self.env().caller(); let action_id = self.next_action_id.get_or_default(); let bond_required = self.get_bond_required(amount, agent); self.actions.set(&action_id, ActionV2 { agent, invoice_id, claim_hash, amount, reasoning_hash, bond_required, bond_posted: U256::zero(), window_end: 0, status: ActionStatusV2::Initiated, challenger: None, fault_class: String::new(), evidence_root: Bytes::from(vec![]) }); self.next_action_id.set(action_id + 1); self.env().emit_event(ActionInitiatedV2 { action_id, agent, invoice_id, amount, bond_required }); action_id }
    pub fn post_bond(&mut self, action_id: u64) { let mut action = self.agent_action(action_id); if action.status != ActionStatusV2::Initiated { self.env().revert(Error::InvalidStatus); } self.vault_ref().deposit_and_lock(action_id, action.agent, action.bond_required); action.bond_posted = action.bond_required; action.status = ActionStatusV2::Bonded; self.actions.set(&action_id, action); }
    pub fn execute_action(&mut self, action_id: u64) { let mut action = self.agent_action(action_id); if action.bond_posted < action.bond_required { self.env().revert(Error::InsufficientBond); } if action.status != ActionStatusV2::Bonded { self.env().revert(Error::InvalidStatus); } self.pool_ref().payout(action.invoice_id, action_id, action.claim_hash.clone(), action.amount); action.window_end = self.env().get_block_time() + self.window_secs.get_or_default() * 1_000; action.status = ActionStatusV2::Executed; self.actions.set(&action_id, action); }
    pub fn challenge_action(&mut self, action_id: u64, fault_class: String, evidence: Bytes) { let mut action = self.actions.get(&action_id).unwrap_or_revert_with(self, Error::ActionNotFound); if action.status != ActionStatusV2::Executed { self.env().revert(Error::InvalidStatus); } if self.env().get_block_time() > action.window_end { self.env().revert(Error::ChallengeWindowClosed); } let verifier = self.fault_verifiers.get(&fault_class).unwrap_or_revert_with(self, Error::UnregisteredVerifier); let confirmed = if fault_class == String::from("duplicate_claim") { DuplicateClaimVerifierV2ContractRef::new(self.env(), verifier).verify(self.pool.get_or_revert_with(Error::ActionNotFound), action_id) } else if fault_class == String::from("delivery_contradiction") { DeliveryContradictionVerifierV2ContractRef::new(self.env(), verifier).verify(self.pool.get_or_revert_with(Error::ActionNotFound), action_id, action.invoice_id, evidence.clone()) } else { false }; if !confirmed { self.env().revert(Error::FaultNotConfirmed); } action.challenger = Some(self.env().caller()); action.status = ActionStatusV2::Challenged; action.fault_class = fault_class.clone(); action.evidence_root = evidence.clone(); self.actions.set(&action_id, action); self.env().emit_event(ActionChallengedV2 { action_id, challenger: self.env().caller(), fault_class, evidence_root: evidence }); }
    pub fn resolve_action(&mut self, action_id: u64) { let mut action = self.actions.get(&action_id).unwrap_or_revert_with(self, Error::ActionNotFound); if action.status == ActionStatusV2::Challenged { let challenger = action.challenger.unwrap_or_revert_with(self, Error::InvalidStatus); let challenger_amount = action.bond_posted * U256::from(self.challenger_bps.get_or_default()) / U256::from(10_000u32); let reserve_amount = action.bond_posted - challenger_amount; let pool = self.pool.get_or_revert_with(Error::ActionNotFound); self.vault_ref().slash(action_id, challenger, pool, self.challenger_bps.get_or_default()); self.pool_ref().add_to_reserve(reserve_amount); let mut rep = self.reputation.get_or_default(&action.agent); rep.slashed += 1; rep.score -= 50; self.reputation.set(&action.agent, rep); action.status = ActionStatusV2::ResolvedSlash; self.actions.set(&action_id, action); self.env().emit_event(ResolvedSlashV2 { action_id, challenger, challenger_amount, reserve_amount, fault_class: self.actions.get(&action_id).unwrap().fault_class, evidence_root: self.actions.get(&action_id).unwrap().evidence_root }); } else if action.status == ActionStatusV2::Executed { if self.env().get_block_time() <= action.window_end { self.env().revert(Error::WindowStillOpen); } self.vault_ref().release(action_id); let mut rep = self.reputation.get_or_default(&action.agent); rep.clean += 1; rep.score += 10; self.reputation.set(&action.agent, rep); action.status = ActionStatusV2::ResolvedRefund; self.actions.set(&action_id, action); } else { self.env().revert(Error::InvalidStatus); } }
    pub fn get_action(&self, action_id: u64) -> ActionV2 { self.actions.get(&action_id).unwrap_or_revert_with(self, Error::ActionNotFound) }
    pub fn get_bond_required(&self, amount: U256, agent: Address) -> U256 { let base = if amount >= U256::from(50_000u64 * TOKEN_UNIT) { 500u32 } else if amount >= U256::from(10_000u64 * TOKEN_UNIT) { 300u32 } else { 200u32 }; let score = self.reputation.get_or_default(&agent).score; let penalty = if score < 0 { score.unsigned_abs().min(300) as u32 } else { 0 }; amount * U256::from(base + penalty) / U256::from(10_000u32) }
}

impl BondsmanControllerV2 { fn owner(&self) { if self.env().caller() != self.owner.get_or_revert_with(Error::NotOwner) { self.env().revert(Error::NotOwner); } } fn agent_action(&self, action_id: u64) -> ActionV2 { let action = self.actions.get(&action_id).unwrap_or_revert_with(self, Error::ActionNotFound); if self.env().caller() != action.agent { self.env().revert(Error::NotAgent); } action } fn vault_ref(&self) -> BondVaultV2ContractRef { BondVaultV2ContractRef::new(self.env(), self.vault.get_or_revert_with(Error::ActionNotFound)) } fn pool_ref(&self) -> InvoicePoolV2ContractRef { InvoicePoolV2ContractRef::new(self.env(), self.pool.get_or_revert_with(Error::ActionNotFound)) } }
